/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\environment\grass.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/environment/grass.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Turbulence" position={[-8.007, 2.209, -0.317]} />
        <mesh name="Grass" geometry={nodes.Grass.geometry} material={materials['Material.001']} scale={7.487} />
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('/grass.gltf')
