/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\big\Orc_Skull.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/big/Orc_Skull.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Orc_Skull" geometry={nodes.Orc_Skull.geometry} material={materials.Atlas} skeleton={nodes.Orc_Skull.skeleton} />
          <skinnedMesh name="Orc_Weapon" geometry={nodes.Orc_Weapon.geometry} material={materials.Atlas} skeleton={nodes.Orc_Weapon.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('/Orc_Skull.gltf')
