/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\flying\Pigeon.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model({ hover, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/flying/Pigeon.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = hover ? "Headbutt" : 'Flying_Idle'
    actions[anim].reset().fadeIn(0.5).play()
    return () => actions[anim].fadeOut(0.5)
  }, [hover])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='CharacterArmature'>
          <primitive object={nodes.Root} />
          <skinnedMesh
            name='Pigeon'
            geometry={nodes.Pigeon.geometry}
            material={materials.Atlas}
            skeleton={nodes.Pigeon.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('/Pigeon.gltf')
