/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\big\Tribal.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model({ hover, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/big/Tribal.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = hover ? "Punch" : 'Idle'
    actions[anim].reset().fadeIn(0.5).play()
    return () => actions[anim].fadeOut(0.5)
  }, [hover])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Tribal" geometry={nodes.Tribal.geometry} material={materials.Atlas} skeleton={nodes.Tribal.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('/Tribal.gltf')
