/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\characters\Ranger.gltf 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model({ hover, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/characters/Ranger.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = hover ? "Walk" : 'Idle'
    actions[anim].reset().fadeIn(0.5).play()
    return () => actions[anim].fadeOut(0.5)
  }, [hover])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Ranger" geometry={nodes.Ranger.geometry} material={materials.Ranger_Texture} skeleton={nodes.Ranger.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('/models/characters/Ranger.gltf')
